[metadata]
version = "1.0"

[versions]
# Adventure
adventure = "4.14.0"
adventure-platform = "4.3.0"

# Platforms
platform-bungeecord = "1.20-R0.1-SNAPSHOT"

# Dependencies
updatelib = "4.0.0"
bstats = "3.0.2"

# Code safety
annotations = "24.0.1"

# Build
build-indra = "3.1.2"
build-errorprone = "2.20.0"
build-errorprone-plugin = "3.1.0"
build-shadow = "8.1.1"

[libraries]
# Adventure
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-platform-bungeecord = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventure-platform" }

# Platforms
platform-bungeecord = { module = "net.md-5:bungeecord-api", version.ref = "platform-bungeecord" }

# Dependencies
updatelib = { module = "dev.hypera:UpdateLib", version.ref = "updatelib" }
bstats-bungeecord = { module = "org.bstats:bstats-bungeecord", version.ref = "bstats" }

# Code safety
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

# Build
build-indra-common = { module = "net.kyori:indra-common", version.ref = "build-indra" }
build-indra-publishing = { module = "net.kyori:indra-publishing-gradle-plugin", version.ref = "build-indra" }
build-errorprone-plugin = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "build-errorprone-plugin" }
build-errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "build-errorprone" }
build-errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "build-errorprone" }

[plugins]
indra-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "build-indra" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "build-shadow" }
